language: java

before_install:
 - chmod +x mvnw

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: [oraclejdk8, oraclejdk9]
      addons: {apt: {packages: [oracle-java8-installer]}}
# TODO openjfx is not supported on trusty, need alternatives
#    - os: linux
#      dist: trusty
#      jdk: openjdk8
#      addons: {apt: {packages: [openjfx]}}
    - os: osx
      osx_image: xcode8.3

sudo: false

script:
 - ./mvnw install -Prelease -DskipTests=true -B -V
 - ./mvnw test
 - ./mvnw clean package -DskipTests=true
